#!/bin/bash

#############################
# Wriiten by Nakada Tokumei #
#############################

echo 'echo $(pwd) > $HOME/.embedded_builder/directory'

if [ ! -f $HOME/.embedded_builder/directory ]; then
    mkdir $HOME/.embedded_builder/
    mkdir -p $HOME/.embedded_builder/pkg
    touch $HOME/.embedded_builder/directory
fi

echo $(pwd) > $HOME/.embedded_builder/directory